spring:
  application:
    name: solen
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss,SSS
    time-zone: Asia/Shanghai
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:data/solen-data.sqlite?busy_timeout=5000&journal_mode=WAL&synchronous=NORMAL
    username: ""
    password: ""
  jpa:
    database-platform: top.fengpingtech.solen.app.persistence.sqlite.SQLiteDialect
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
      schema-locations: [ classpath:schema-sqlite.sql ]
solen:
  server:
    port: 7889
  event:
    writer:
      queue-capacity: 20000
      batch-size: 200
      flush-interval-ms: 200
  auth:
    tenants:
      - app-key: test
        secret-key: test
        pass-key: test
        roles: [ USER ]
        device-patterns: [ "555**", "400**" ]
      - app-key: admin
        secret-key: 123asdsecret123asdfadmin
        pass-key: admin
        roles: [ ADMIN ]
        device-patterns: ["**"]
    jwt:
      secret: d41d8cd98f00b204e9800998ecf8427e
      ttl: 3600000
      issuer: http://iot-online.fengping-tech.top

logging:
  file:
    path: log
  level:
    top.fengpingtech.solen: debug
