--CREATE TABLE category (
--
--  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
--
--  name varchar(255) DEFAULT NULL,
--
--  PRIMARY KEY (id)
--
--) ;


insert into CATEGORY( nam ) values ( '111' );
--insert into category( `name`) values ( '111' );
--insert into category( `name`) values ( '111' );
--insert into category( `name`) values ( '111' );